logging:
  level:
    com.meawallet.smartrequest: DEBUG

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1