server:
  port: 8080

logging:
  level:
    com.meawallet.smartrequest: DEBUG

weather-api:
  weather-url: https://api.met.no/weatherapi/locationforecast/2.0/compact
  user-agent: SmartRequest1.0

spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:smart_app_db;DB_CLOSE_DELAY=-1
  liquibase:
    user: sa
    password:
    url: jdbc:h2:mem:smart_app_db;DB_CLOSE_DELAY=-1
    change-log: classpath:db/master.xml
  h2:
    console:
      enabled: true
      path: /h2-console